# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = glTFLoader
DESTDIR = ../x64/Debug
CONFIG += staticlib debug
DEFINES += GLTFLOADER_LIB BUILD_STATIC
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(glTFLoader.pri)
